name: reclaim_sdk
description: Reclaim SDK provides a way to let your users import data from other websites into your app in a secure, privacy preserving manner using zero knowledge proofs right in your Flutter Application.
version: 3.0.0
homepage: https://www.reclaimprotocol.org/
repository: https://github.com/reclaimprotocol/reclaim-flutter-sdk.git

scripts:
  update_changelog: dart update_changelog.dart

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.1.0
  url_launcher: ^6.2.5
  yaml: ^3.1.2
  web3dart: ^2.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

